### ISSUE TITLE
BTC/CAD currency pair does not work

### ISSUE THREAD

**Issue by IntegersOfK** [razem-io/BittyDream#5]
I love your daydream app but the BTC/CAD currency pair no longer works because the API for CaVirtex is now offline after it was purchased by Kraken.

The Kraken dropdown could display the option for Canadian dollars now that the information is available from their API.

If you can't get around to it I'll try to figure it out for a pull request. Thanks for the great daydreams!

**Comment by razem-io** [comment]
Let me have a look. I will have some time at the weekend to check. Sadly I lost the deployment keys but I am up for a version 2 of BittyDream.

**Comment by IntegersOfK** [comment]
Blast, those keys are the worst eh? I made the mistake of using the same keystore for all my apps, from the stupid tests to the production deployed apks on the Play Store. Now I can't really hand the good apps to a new developer/team because it would essentially give away all the other keys to them too.

So anyway if you're able to rejig this into a new daydream app I'm the first in line to install it! Thanks for your hard work. :dancers:

**Comment by razem-io** [comment]
@IntegersOfK this should be fixed now. Could you check if it works for you. You can download a build here -> https://github.com/razem-io/BittyDream/releases

**Comment by IntegersOfK** [comment]
Maybe I'm a little ahead of the times here using Android N beta with my Nexus 6P, but I'm sorry to report it doesn't work on this device. If I go into Daydream Settings, select BittyDream, then hit "Start now" from the extra options, it lags a second and then shows me a blank black screen.

This is the case with any of the exchanges or currencies selected, I tried rebooting and reinstalling several times from your release linked above. I'm on a little trip away from home at the moment otherwise I'd be happy to take a look at logcat output and try a stab at debugging.

**Comment by razem-io** [comment]
Ok. That logcat output would be neat! I opened a new issue regarding this topic -> https://github.com/razem-io/BittyDream/issues/6
